"""Render the generated sections into docs/.

Only writes files it owns: docs/publications/, docs/topics/, docs/thinking/,
docs/publications.html, docs/what-we-are-thinking.html, docs/sitemap.xml. The
hand-written pages (index.html, about.html, the bios) are never touched — their
nav links to the generated sections are maintained by hand in them.
"""
from __future__ import annotations

import json
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined
from markupsafe import Markup

from .model import Paper, Theme
from .posts import Post

BASE_URL = "https://ciunit.org"
ORG_NAME = "Conceptual Investigations Unit"

GENERATED_BANNER = (
    "<!-- GENERATED by ciunit_gen — do not edit. "
    "Source: {source}. Rebuild: python -m ciunit_gen -->"
)


def _jsonld(data: dict) -> Markup:
    """Serialise JSON-LD for embedding in a <script> element.

    Returned as Markup so autoescaping leaves the quotes alone — HTML-escaping
    the payload would turn every '"' into '&#34;' and render the block unparseable.
    Escaping '<' to \\u003c is what keeps that safe: no string value can emit a
    literal '</script>' and terminate the block early.
    """
    return Markup(json.dumps(data, indent=2, ensure_ascii=False).replace("<", "\\u003c"))


def make_env(templates_dir: Path) -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=True,             # content files are plain text; never trust them with markup
        undefined=StrictUndefined,   # a typo'd variable should fail the build, not render blank
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["jsonld"] = _jsonld
    return env


def paper_jsonld(paper: Paper) -> dict:
    """WebPage describing a ScholarlyArticle.

    The page is *about* the article; it is not the article itself, so the article
    hangs off mainEntity and is keyed by its DOI.
    """
    article = {
        "@type": "ScholarlyArticle",
        "@id": paper.doi_url,
        "name": paper.title,
        "headline": paper.title,
        "author": [{"@type": "Person", "name": a} for a in paper.authors],
        "datePublished": paper.date or str(paper.year),
        "isPartOf": {"@type": "Periodical", "name": paper.journal},
        "identifier": {"@type": "PropertyValue", "propertyID": "DOI", "value": paper.doi},
        "sameAs": paper.doi_url,
    }
    if paper.volume:
        article["volumeNumber"] = paper.volume
    if paper.pages:
        article["pagination"] = paper.pages
    return {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "url": f"{BASE_URL}/{paper.url_path}",
        "name": paper.title,
        "description": paper.description,
        "publisher": {"@type": "Organization", "name": ORG_NAME, "url": BASE_URL},
        "mainEntity": article,
    }


def theme_jsonld(theme: Theme, papers: list[Paper]) -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "url": f"{BASE_URL}/{theme.url_path}",
        "name": theme.title,
        "description": theme.description,
        "publisher": {"@type": "Organization", "name": ORG_NAME, "url": BASE_URL},
        "mainEntity": {
            "@type": "Question",
            "name": theme.question,
            "acceptedAnswer": {"@type": "Answer", "text": theme.short_answer},
        },
        "citation": [
            {"@type": "ScholarlyArticle", "@id": p.doi_url, "name": p.title}
            for p in papers
        ],
    }


def post_jsonld(post: Post, paper: Paper | None) -> dict:
    """BlogPosting — not the publications' WebPage + mainEntity ScholarlyArticle.

    On a publication page the page is *about* an article that lives elsewhere. On
    a post the page *is* the work, so it types as the creative work itself and
    the paper it discusses hangs off `about`. That distinction is what tells an
    answer engine this is our commentary on a specific paper rather than a
    second copy of the paper's own claims.
    """
    data = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "@id": f"{BASE_URL}/{post.url_path}",
        "url": f"{BASE_URL}/{post.url_path}",
        "headline": post.title,
        "description": post.description,
        "abstract": post.key_point,
        "datePublished": post.date,
        "author": [{"@type": "Person", "name": a} for a in post.authors],
        "publisher": {"@type": "Organization", "name": ORG_NAME, "url": BASE_URL},
        "isPartOf": {
            "@type": "Blog",
            "name": f"What We Are Thinking — {ORG_NAME}",
            "url": f"{BASE_URL}/what-we-are-thinking.html",
        },
    }
    if paper:
        article = {
            "@type": "ScholarlyArticle",
            "@id": paper.doi_url,
            "name": paper.title,
            "url": f"{BASE_URL}/{paper.url_path}",
        }
        data["about"] = article
        data["citation"] = article
    return data


class Renderer:
    def __init__(self, root: Path):
        self.root = root
        self.docs = root / "docs"
        self.env = make_env(root / "src" / "ciunit_gen" / "templates")
        self.written: list[Path] = []

    def _write(self, rel: str, text: str) -> None:
        path = self.docs / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not text.endswith("\n"):
            text += "\n"
        path.write_text(text, encoding="utf-8")
        self.written.append(path)

    def render_paper(self, paper: Paper, themes: dict[str, Theme],
                     by_id: dict[str, Paper], posts: list[Post] | None = None) -> None:
        html = self.env.get_template("paper.html.j2").render(
            banner=Markup(GENERATED_BANNER).format(source=f"content/publications/{paper.id}.yaml"),
            paper=paper,
            up="../",
            canonical=f"{BASE_URL}/{paper.url_path}",
            themes=[themes[t] for t in paper.themes if t in themes],
            related=[by_id[r] for r in paper.related if r in by_id],
            # Posts about this publication. Both pages are generated, so the
            # link cannot drift out of step with the post's `about` field.
            posts=posts or [],
            jsonld=paper_jsonld(paper),
        )
        self._write(paper.url_path, html)

    def render_theme(self, theme: Theme, papers: list[Paper],
                     by_id: dict[str, Paper]) -> None:
        cited = [by_id[e.paper] for e in theme.evidence if e.paper in by_id]
        seen, unique = set(), []
        for p in cited + papers:
            if p.id not in seen:
                seen.add(p.id)
                unique.append(p)
        html = self.env.get_template("theme.html.j2").render(
            banner=Markup(GENERATED_BANNER).format(source="content/themes.yaml"),
            theme=theme,
            up="../",
            canonical=f"{BASE_URL}/{theme.url_path}",
            papers=papers,
            by_id=by_id,
            jsonld=theme_jsonld(theme, unique),
        )
        self._write(theme.url_path, html)

    def render_index(self, papers: list[Paper], themes: list[Theme]) -> None:
        # One flat grid, newest first. `papers` already arrives in that order.
        # The themes are no longer section headings here, so they are listed as a
        # link strip instead: this page is the only route to them from the nav.
        html = self.env.get_template("paper-index.html.j2").render(
            banner=Markup(GENERATED_BANNER).format(source="content/publications/*.yaml"),
            up="",
            canonical=f"{BASE_URL}/publications.html",
            papers=papers,
            themes=themes,
            jsonld={
                "@context": "https://schema.org",
                "@type": "CollectionPage",
                "url": f"{BASE_URL}/publications.html",
                "name": f"What We Publish — {ORG_NAME}",
                "description": (
                    f"Plain-language summaries of {len(papers)} peer-reviewed publications "
                    f"by researchers of the {ORG_NAME}, each with its key finding, "
                    "a key figure, and a link to the published article."
                ),
                "publisher": {"@type": "Organization", "name": ORG_NAME, "url": BASE_URL},
                # hasPart is unordered, so the chronological order of the page
                # would be invisible to a consumer. ItemList states it.
                "mainEntity": {
                    "@type": "ItemList",
                    "itemListOrder": "https://schema.org/ItemListOrderDescending",
                    "numberOfItems": len(papers),
                    "itemListElement": [
                        {"@type": "ListItem", "position": i,
                         "url": f"{BASE_URL}/{p.url_path}", "name": p.title}
                        for i, p in enumerate(papers, 1)
                    ],
                },
            },
        )
        self._write("publications.html", html)

    def render_post(self, post: Post, by_id: dict[str, Paper],
                    by_theme: dict[str, Theme]) -> None:
        paper = by_id.get(post.about) if post.about else None
        html = self.env.get_template("post.html.j2").render(
            banner=Markup(GENERATED_BANNER).format(
                source=f"content/posts/{post.source_path.name}"),
            post=post,
            up="../",
            canonical=f"{BASE_URL}/{post.url_path}",
            paper=paper,
            themes=[by_theme[t] for t in post.themes if t in by_theme],
            jsonld=post_jsonld(post, paper),
        )
        self._write(post.url_path, html)

    def render_post_index(self, posts: list[Post]) -> None:
        # `posts` arrives newest first, which the ItemList below states
        # explicitly for the same reason render_index does.
        html = self.env.get_template("post-index.html.j2").render(
            banner=Markup(GENERATED_BANNER).format(source="content/posts/*.md"),
            up="",
            canonical=f"{BASE_URL}/what-we-are-thinking.html",
            posts=posts,
            jsonld={
                "@context": "https://schema.org",
                "@type": "Blog",
                "url": f"{BASE_URL}/what-we-are-thinking.html",
                "name": f"What We Are Thinking — {ORG_NAME}",
                "description": (
                    f"{len(posts)} post(s) by researchers of the {ORG_NAME}: "
                    "walk-throughs of our own publications, and commentary on "
                    "questions of climate, energy, and how research works."
                ),
                "publisher": {"@type": "Organization", "name": ORG_NAME, "url": BASE_URL},
                "mainEntity": {
                    "@type": "ItemList",
                    "itemListOrder": "https://schema.org/ItemListOrderDescending",
                    "numberOfItems": len(posts),
                    "itemListElement": [
                        {"@type": "ListItem", "position": i,
                         "url": f"{BASE_URL}/{p.url_path}", "name": p.title}
                        for i, p in enumerate(posts, 1)
                    ],
                },
            },
        )
        self._write("what-we-are-thinking.html", html)

    def render_sitemap(self, papers: list[Paper], themes: list[Theme],
                       posts: list[Post], static_pages: list[str]) -> None:
        urls = [f"{BASE_URL}/{p}" for p in static_pages]
        urls += [f"{BASE_URL}/publications.html"]
        urls += [f"{BASE_URL}/{t.url_path}" for t in themes]
        urls += [f"{BASE_URL}/{p.url_path}" for p in papers]
        urls += [f"{BASE_URL}/what-we-are-thinking.html"]
        urls += [f"{BASE_URL}/{p.url_path}" for p in posts]
        # No <lastmod>: the output is committed to git, so the build must be
        # reproducible. A build-date lastmod would churn the file every day.
        xml = self.env.get_template("sitemap.xml.j2").render(urls=urls)
        self._write("sitemap.xml", xml)
