"""Per-page status report — PAGES-STATUS.md.

Answers "what state is each publication page in?", with particular attention to figure
resolution, so that low-resolution images can be found and replaced. Figures
extracted from a PDF vary enormously in usable resolution depending on whether
the source was vector art or a scan, and that is not visible from the YAML.
"""
from __future__ import annotations

import struct
from pathlib import Path

from .model import Paper, Theme

# Publication pages render inside .bio, which is 820 px wide. Anything at or above
# ~1200 px still looks sharp on a 1.5x display; below ~500 px is visibly soft.
QUALITY = [(1200, "good"), (800, "adequate"), (500, "low"), (0, "very low")]


def image_size(path: Path) -> tuple[int, int] | None:
    """(width, height) for PNG, WebP, JPEG. Header parsing — no dependencies."""
    try:
        data = path.read_bytes()
    except OSError:
        return None

    if data[:8] == b"\x89PNG\r\n\x1a\n" and data[12:16] == b"IHDR":
        return struct.unpack(">II", data[16:24])

    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        chunk = data[12:16]
        if chunk == b"VP8X":
            w = int.from_bytes(data[24:27], "little") + 1
            h = int.from_bytes(data[27:30], "little") + 1
            return w, h
        if chunk == b"VP8L":
            b = int.from_bytes(data[21:25], "little")
            return (b & 0x3FFF) + 1, ((b >> 14) & 0x3FFF) + 1
        if chunk == b"VP8 ":
            return (int.from_bytes(data[26:28], "little") & 0x3FFF,
                    int.from_bytes(data[28:30], "little") & 0x3FFF)

    if data[:2] == b"\xff\xd8":                       # JPEG
        i = 2
        while i < len(data) - 9:
            if data[i] != 0xFF:
                i += 1
                continue
            marker = data[i + 1]
            if marker in (0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7,
                          0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF):
                h, w = struct.unpack(">HH", data[i + 5:i + 9])
                return w, h
            i += 2 + int.from_bytes(data[i + 2:i + 4], "big")
    return None


def quality(width: int | None) -> str:
    if not width:
        return "unknown"
    return next(label for lo, label in QUALITY if width >= lo)


def build(papers: list[Paper], themes: list[Theme], root: Path) -> str:
    fig_dir = root / "docs" / "publications" / "figures"
    by_theme = {t.id: t for t in themes}

    rows, no_fig, low = [], [], []
    for p in sorted(papers, key=lambda x: (-x.year, x.id)):
        if p.figure:
            path = fig_dir / p.figure.file
            size = image_size(path)
            w, h = size if size else (None, None)
            q = quality(w)
            kb = round(path.stat().st_size / 1024) if path.exists() else 0
            fig = (f"{w}×{h}" if size else "**missing file**")
            src = p.figure.source or "unrecorded"
            lic = p.figure.license
            if q in ("low", "very low", "unknown"):
                low.append(p.id)
        else:
            fig, q, kb, src, lic = "—", "none", 0, "—", "—"
            no_fig.append(p.id)
        rows.append((p, fig, q, kb, src, lic))

    lines = [
        "# Publication page status",
        "",
        "Generated by `python -m ciunit_gen --report` — do not edit by hand.",
        "One row per published publication page.",
        "",
        "**Figure quality** is judged against the 820 px content column: `good`",
        "is 1200 px wide or more, `adequate` 800–1199, `low` 500–799, `very low`",
        "below 500. Anything `low` or worse is worth replacing with a",
        "higher-resolution source.",
        "",
        f"- **{len(papers)}** publication pages across **{len(themes)}** themes",
        f"- **{len(papers) - len(no_fig)}** have a figure, **{len(no_fig)}** do not",
        f"- **{len(low)}** have a figure below `adequate` resolution",
        f"- **{sum(1 for p in papers if p.needs_review)}** are flagged `needs_review`",
        "",
    ]
    if low:
        lines += ["## Figures worth replacing", "",
                  *(f"- `{pid}`" for pid in low), ""]
    if any(p.needs_review for p in papers):
        lines += ["## Flagged for author review", "",
                  *(f"- `{p.id}` — claims not yet verified against the publication"
                    for p in papers if p.needs_review), ""]

    lines += ["## Pages", "",
              "| Page | Year | Theme | Figure | Quality | Size | Source | Licence | Review |",
              "| --- | ---: | --- | --- | --- | ---: | --- | --- | --- |"]
    for p, fig, q, kb, src, lic in rows:
        theme = ", ".join(by_theme[t].title for t in p.themes if t in by_theme) or "—"
        flag = "⚠️" if p.needs_review else ""
        lines.append(
            f"| [{p.id}](docs/{p.url_path})<br><sub>{p.short_citation}</sub> | {p.year} "
            f"| <sub>{theme}</sub> | {fig} | `{q}` | {kb or ''}{' KB' if kb else ''} "
            f"| <sub>{src}</sub> | <sub>{lic}</sub> | {flag} |")
    return "\n".join(lines) + "\n"
